name: timestracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  image_picker: ^1.0.7
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.1
  table_calendar: ^3.0.9
  timeline_tile: ^2.0.0
  fl_chart: ^0.66.0
  uuid: ^4.3.3
  flutter_swipe_action_cell: ^3.1.3
  device_preview: ^1.1.0


flutter:
  uses-material-design: true
